### ISSUE TITLE
Client/ npm start fails

### ISSUE THREAD

**Issue by zera555** [endel/babylonjs-multiplayer-boilerplate#7]
Using v8.9.4 on MacOS. npm 5.6.0

`npm install` in both client/ and server/ seems to work. `npm start` in server/ seems to work, but when I run `npm start` in the client/ directory, I get this error/output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle babylonjs-colyseus-client@1.0.0~prestart: babylonjs-colyseus-client@1.0.0
6 info lifecycle babylonjs-colyseus-client@1.0.0~start: babylonjs-colyseus-client@1.0.0
7 verbose lifecycle babylonjs-colyseus-client@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle babylonjs-colyseus-client@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:babylonjs-multiplayer-boilerplate/client/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:
9 verbose lifecycle babylonjs-colyseus-client@1.0.0~start: CWD: babylonjs-multiplayer-boilerplate/client
10 silly lifecycle babylonjs-colyseus-client@1.0.0~start: Args: [ '-c', 'webpack-dev-server --host 0.0.0.0' ]
11 silly lifecycle babylonjs-colyseus-client@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle babylonjs-colyseus-client@1.0.0~start: Failed to exec start script
13 verbose stack Error: babylonjs-colyseus-client@1.0.0 start: `webpack-dev-server --host 0.0.0.0`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid babylonjs-colyseus-client@1.0.0
15 verbose cwd babylonjs-multiplayer-boilerplate/client
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error babylonjs-colyseus-client@1.0.0 start: `webpack-dev-server --host 0.0.0.0`
22 error Exit status 1
23 error Failed at the babylonjs-colyseus-client@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by endel** [comment]
Hi @zera555, thanks for reporting. I've just updated `webpack-cli` in the `package.json` which fixes this.
